/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IdImport } from './routes/$id'
import { Route as IndexImport } from './routes/index'
import { Route as SearchSeriesTitleImport } from './routes/search/series.$title'
import { Route as SearchSeriesIdImport } from './routes/search/series.$id'
import { Route as SearchMoviesTitleImport } from './routes/search/movies.$title'
import { Route as SearchMovieIdImport } from './routes/search/movie.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IdRoute = IdImport.update({
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchSeriesTitleRoute = SearchSeriesTitleImport.update({
  path: '/search/series/$title',
  getParentRoute: () => rootRoute,
} as any)

const SearchSeriesIdRoute = SearchSeriesIdImport.update({
  path: '/search/series/$id',
  getParentRoute: () => rootRoute,
} as any)

const SearchMoviesTitleRoute = SearchMoviesTitleImport.update({
  path: '/search/movies/$title',
  getParentRoute: () => rootRoute,
} as any)

const SearchMovieIdRoute = SearchMovieIdImport.update({
  path: '/search/movie/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/search/movie/$id': {
      id: '/search/movie/$id'
      path: '/search/movie/$id'
      fullPath: '/search/movie/$id'
      preLoaderRoute: typeof SearchMovieIdImport
      parentRoute: typeof rootRoute
    }
    '/search/movies/$title': {
      id: '/search/movies/$title'
      path: '/search/movies/$title'
      fullPath: '/search/movies/$title'
      preLoaderRoute: typeof SearchMoviesTitleImport
      parentRoute: typeof rootRoute
    }
    '/search/series/$id': {
      id: '/search/series/$id'
      path: '/search/series/$id'
      fullPath: '/search/series/$id'
      preLoaderRoute: typeof SearchSeriesIdImport
      parentRoute: typeof rootRoute
    }
    '/search/series/$title': {
      id: '/search/series/$title'
      path: '/search/series/$title'
      fullPath: '/search/series/$title'
      preLoaderRoute: typeof SearchSeriesTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  IdRoute,
  AboutRoute,
  SearchMovieIdRoute,
  SearchMoviesTitleRoute,
  SearchSeriesIdRoute,
  SearchSeriesTitleRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$id",
        "/about",
        "/search/movie/$id",
        "/search/movies/$title",
        "/search/series/$id",
        "/search/series/$title"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$id": {
      "filePath": "$id.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/search/movie/$id": {
      "filePath": "search/movie.$id.tsx"
    },
    "/search/movies/$title": {
      "filePath": "search/movies.$title.tsx"
    },
    "/search/series/$id": {
      "filePath": "search/series.$id.tsx"
    },
    "/search/series/$title": {
      "filePath": "search/series.$title.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
