services:
  frontend:
    container_name: movi_fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./frontend
        target: /app
