import type { Content } from "./models/content.models";

export const fakeContent: Content[] = [
  {
    id: "1",
    title: "BATMAN",
    img: "BatmanPoster",
    date: "2022",
    running: "176MIN",
    director: "Matt Reeves",
    type: "movie",
  },
  {
    id: "2",
    title: "BOHEMIAN RHAPSODY",
    img: "BohemianPoster",
    date: "2018",
    running: "134MIN",
    director: "Bryan Singer, Dexter Fletcher",
    type: "movie",
  },
  {
    id: "3",
    title: "THE LAST OF US",
    img: "TLOUPoster",
    date: "2023",
    running: "seasons 1",
    director: "Neil Druckmann, Craig Mazin",
    type: "series",
  },
  {
    id: "4",
    title: "JOKER",
    img: "JokerPoster",
    date: "2019",
    running: "122MIN",
    director: "Todd Phillips",
    type: "movie",
  },
  {
    id: "5",
    title: "FALLOUT",
    img: "FalloutPoster",
    date: "2024",
    running: "seasons 1",
    director: "Geneva Robertson-Dworet, Graham Wagner",
    type: "series",
  },
  {
    id: "6",
    title: "ARCANE",
    img: "ArcanePoster",
    date: "2021",
    running: "seasons 1",
    director: "Christian Linke, Alex Yee",
    type: "series",
  },
  {
    id: "7",
    title: "CHERNOBYL",
    img: "ChernobylPoster",
    date: "2019",
    running: "seasons 1",
    director: "Craig Mazin",
    type: "series",
  },
  {
    id: "8",
    title: "RICK AND MORTY",
    img: "RickAndMortyPoster",
    date: "2013",
    running: "seasons 7",
    director: "Justin Roiland, Dan Harmon",
    type: "series",
  },
  {
    id: "9",
    title: "SPIDER MAN ACROSS THE SPIDER VERSE",
    img: "SpiderManPoster",
    date: "2023",
    running: "140MIN",
    director: "Kemp Powers, Justin K. Thompson, Joaquim Dos Santos",
    type: "movie",
  },
  {
    id: "10",
    title: "THE BOYS",
    img: "TheBoysPoster",
    date: "2019",
    running: "seasons 4",
    director: "Eric Kripke",
    type: "series",
  },
];
